import streamlit as st
import plotly.graph_objects as go
import numpy as np
import json

# Safely import anastruct
try:
    from anastruct import SystemElements
except ImportError:
    st.error("Missing dependency: anastruct. Please run `pip install anastruct`.")
    st.stop()

st.set_page_config(page_title="Bridge SHM Simulator", layout="wide")

st.title("🌉 Bridge SHM Simulator: Moving Load")
st.markdown("1. Place sensors. 2. Run the simulation. 3. Watch the structural response!")

SENSOR_TYPES = {
    "Accelerometer": {"color": "purple", "symbol": "triangle-up", "size": 20},
    "Strain Gauge": {"color": "green", "symbol": "square", "size": 18},
    "Displacement": {"color": "orange", "symbol": "diamond-cross", "size": 22},
}

default_bridge = {
    "nodes": [[0, 0], [4, 0], [8, 0], [12, 0], [2, 3], [6, 3], [10, 3]],
    "members": [[1, 2], [2, 3], [3, 4], [5, 6], [6, 7], [1, 5], [2, 5], [2, 6], [3, 6], [3, 7], [4, 7]]
}


def validate_bridge_json(data):
    if not isinstance(data, dict):
        raise ValueError("JSON must be an object with 'nodes' and 'members'.")

    nodes = data.get("nodes")
    members = data.get("members")

    if not isinstance(nodes, list) or len(nodes) < 2:
        raise ValueError("'nodes' must be a list with at least 2 [x, y] points.")
    if not isinstance(members, list) or len(members) == 0:
        raise ValueError("'members' must be a non-empty list of [start_node, end_node].")

    cleaned_nodes = []
    for idx, node in enumerate(nodes, start=1):
        if not isinstance(node, list) or len(node) != 2:
            raise ValueError(f"Node {idx} must be [x, y].")
        try:
            x = float(node[0])
            y = float(node[1])
        except (TypeError, ValueError) as exc:
            raise ValueError(f"Node {idx} has non-numeric coordinates.") from exc
        cleaned_nodes.append([x, y])

    cleaned_members = []
    n_nodes = len(cleaned_nodes)
    for idx, member in enumerate(members, start=1):
        if not isinstance(member, list) or len(member) != 2:
            raise ValueError(f"Member {idx} must be [start_node, end_node].")
        n1, n2 = member
        if not isinstance(n1, int) or not isinstance(n2, int):
            raise ValueError(f"Member {idx} node references must be integers.")
        if not (1 <= n1 <= n_nodes and 1 <= n2 <= n_nodes):
            raise ValueError(f"Member {idx} references nodes outside 1..{n_nodes}.")
        cleaned_members.append([n1, n2])

    return {"nodes": cleaned_nodes, "members": cleaned_members}


def sensor_target_exists(target, bridge_data):
    if not isinstance(target, str) or "_" not in target:
        return False
    obj, id_str = target.split("_", 1)
    if not id_str.isdigit():
        return False

    target_id = int(id_str)
    if obj == "Joint":
        return 1 <= target_id <= len(bridge_data["nodes"])
    if obj == "Beam":
        return 1 <= target_id <= len(bridge_data["members"])
    return False


st.subheader("Bridge Definition")
uploaded_json = st.file_uploader("Upload bridge JSON", type=["json"])
pasted_json = st.text_area(
    "Or paste bridge JSON generated by LLM",
    height=140,
    placeholder='{"nodes": [[0,0], [4,0]], "members": [[1,2]]}',
)

bridge_data = default_bridge
custom_json_text = None
if uploaded_json is not None:
    custom_json_text = uploaded_json.getvalue().decode("utf-8")
elif pasted_json.strip():
    custom_json_text = pasted_json

if custom_json_text:
    try:
        parsed_bridge = json.loads(custom_json_text)
        bridge_data = validate_bridge_json(parsed_bridge)
        st.success("Using custom bridge JSON.")
    except Exception as exc:
        st.warning(f"Invalid custom JSON ({exc}). Using default bridge.")
else:
    st.caption("No custom JSON provided. Using default bridge.")

st.caption(
    f"Bridge loaded: {len(bridge_data['nodes'])} nodes, {len(bridge_data['members'])} members"
)

if "sensors" not in st.session_state:
    st.session_state.sensors = {}
elif not isinstance(st.session_state.sensors, dict):
    st.session_state.sensors = {}
else:
    st.session_state.sensors = {
        location: sensor_type
        for location, sensor_type in st.session_state.sensors.items()
        if isinstance(location, str)
        and "_" in location
        and location.split("_", 1)[1].isdigit()
        and sensor_type in SENSOR_TYPES
        and sensor_target_exists(location, bridge_data)
    }

def draw_bridge(data):
    fig = go.Figure()
    nodes = data["nodes"]
    
    # Draw Beams
    for i, member in enumerate(data["members"], start=1):
        n1, n2 = nodes[member[0] - 1], nodes[member[1] - 1]
        fig.add_trace(go.Scatter(x=[n1[0], n2[0]], y=[n1[1], n2[1]], mode="lines", line=dict(color="black", width=3), hoverinfo="skip", showlegend=False))

    # Clickable Beam Midpoints
    mid_xs, mid_ys, mid_texts, mid_customdata = [], [], [], []
    for i, member in enumerate(data["members"], start=1):
        n1, n2 = nodes[member[0] - 1], nodes[member[1] - 1]
        mid_xs.append((n1[0] + n2[0]) / 2)
        mid_ys.append((n1[1] + n2[1]) / 2)
        mid_texts.append(f"Beam {i}")
        mid_customdata.append(f"Beam_{i}")

    fig.add_trace(go.Scatter(x=mid_xs, y=mid_ys, mode="markers+text", marker=dict(symbol="diamond", size=10, color="lightgray"), text=mid_texts, textposition="top center", customdata=mid_customdata, name="Clickable Beams"))

    # Clickable Joints
    node_xs, node_ys = [n[0] for n in nodes], [n[1] for n in nodes]
    node_texts = [f"Joint {i}" for i in range(1, len(nodes) + 1)]
    node_customdata = [f"Joint_{i}" for i in range(1, len(nodes) + 1)]

    fig.add_trace(go.Scatter(x=node_xs, y=node_ys, mode="markers+text", marker=dict(symbol="circle", size=14, color="blue"), text=node_texts, textposition="bottom center", customdata=node_customdata, name="Clickable Joints"))

    # Overlay Placed Sensors
    if st.session_state.sensors:
        for sensor_type, config in SENSOR_TYPES.items():
            s_xs, s_ys, s_hover = [], [], []
            for target, placed_type in st.session_state.sensors.items():
                if placed_type == sensor_type:
                    if not isinstance(target, str) or "_" not in target:
                        continue

                    target_obj, target_id = target.split("_", 1)
                    if not target_id.isdigit():
                        continue
                    target_id = int(target_id)
                    if target_obj == "Joint":
                        s_xs.append(nodes[target_id - 1][0])
                        s_ys.append(nodes[target_id - 1][1])
                    elif target_obj == "Beam":
                        member = data["members"][target_id - 1]
                        n1, n2 = nodes[member[0] - 1], nodes[member[1] - 1]
                        s_xs.append((n1[0] + n2[0]) / 2)
                        s_ys.append((n1[1] + n2[1]) / 2)
                    s_hover.append(f"{sensor_type} on {target}")

            if s_xs:
                fig.add_trace(go.Scatter(x=s_xs, y=s_ys, mode="markers", marker=dict(symbol=config["symbol"], size=config["size"], color=config["color"], line=dict(width=2, color="black")), name=sensor_type, text=s_hover, hoverinfo="text"))

    fig.update_layout(xaxis=dict(visible=False), yaxis=dict(visible=False, scaleanchor="x", scaleratio=1), margin=dict(l=20, r=20, t=20, b=20), clickmode="event+select", dragmode=False)
    return fig

# --- SIMULATION ENGINE ---
def run_moving_load(bridge_data, sensors, steps=40):
    # Use nodes on the lowest chord (minimum y) as the moving-load path.
    min_y = min(node[1] for node in bridge_data["nodes"])
    bottom_nodes = [
        idx + 1
        for idx, node in enumerate(bridge_data["nodes"])
        if abs(node[1] - min_y) < 1e-9
    ]
    bottom_nodes = sorted(bottom_nodes, key=lambda node_id: bridge_data["nodes"][node_id - 1][0])
    if len(bottom_nodes) < 2:
        raise ValueError("Bridge must have at least 2 nodes on the lowest chord for moving-load simulation.")

    bottom_xs = [bridge_data["nodes"][i - 1][0] for i in bottom_nodes]
    min_x, max_x = min(bottom_xs), max(bottom_xs)
    
    x_positions = np.linspace(min_x, max_x, steps)
    valid_sensors = {
        target: sensor_type
        for target, sensor_type in sensors.items()
        if isinstance(target, str)
        and "_" in target
        and target.split("_", 1)[1].isdigit()
        and sensor_type in SENSOR_TYPES
    }
    results = {s: [] for s in valid_sensors}
    
    # Progress bar for UI
    progress_bar = st.progress(0)
    
    for step_idx, x in enumerate(x_positions):
        ss = SystemElements(EA=15000, EI=5000)
        
        # Build structure
        for member in bridge_data["members"]:
            n1 = bridge_data["nodes"][member[0]-1]
            n2 = bridge_data["nodes"][member[1]-1]
            ss.add_element(location=[n1, n2])
            
        ss.add_support_hinged(node_id=1)
        ss.add_support_roll(node_id=bottom_nodes[-1], direction=2) # 2 = Y-direction
        
        # Distribute Load (-100 kN) using Lever Rule
        for i in range(len(bottom_xs)-1):
            if bottom_xs[i] <= x <= bottom_xs[i+1]:
                L = bottom_xs[i+1] - bottom_xs[i]
                P_left = -100.0 * (bottom_xs[i+1] - x) / L
                P_right = -100.0 * (x - bottom_xs[i]) / L
                ss.point_load(node_id=bottom_nodes[i], Fy=P_left)
                ss.point_load(node_id=bottom_nodes[i+1], Fy=P_right)
                break
                
        ss.solve() # Analyze the frame!
        
        # Extract Sensor Data
        for sensor_target, s_type in valid_sensors.items():
            t_obj, t_id = sensor_target.split("_", 1)
            t_id = int(t_id)
            
            try:
                if t_obj == "Joint":
                    disp = ss.get_node_displacements(node_id=t_id)
                    results[sensor_target].append(disp['uy'] if disp else 0.0)
                elif t_obj == "Beam":
                    # Using axial force (N) as a proxy for Strain
                    elem_results = ss.get_element_results(element_id=t_id)
                    results[sensor_target].append(elem_results[0]['N'] if elem_results else 0.0)
            except Exception:
                results[sensor_target].append(0.0) # Fallback if extraction fails
                
        progress_bar.progress((step_idx + 1) / steps)
        
    progress_bar.empty()
    
    # Post-process Accelerometers
    dt = 0.1 
    for sensor_target, s_type in valid_sensors.items():
        if s_type == "Accelerometer":
            disps = np.array(results[sensor_target])
            accels = np.gradient(np.gradient(disps, dt), dt)
            results[sensor_target] = accels.tolist()
            
    return x_positions, results

# --- UI LAYOUT ---
col1, col2 = st.columns([2, 1])

with col2:
    st.subheader("Sensor Tools")
    active_sensor = st.radio("🛠️ Active Sensor:", list(SENSOR_TYPES.keys()))
    
    if st.button("🗑️ Clear All Sensors"):
        st.session_state.sensors = {}
        st.rerun()
        
    st.divider()
    st.markdown("**Placed Sensors:**")
    for location, s_type in st.session_state.sensors.items():
        st.write(f"- {s_type} at {location}")
        
    st.divider()
    # THE BIG BUTTON
    run_sim = st.button("🚀 Run Moving Load Simulation", type="primary", use_container_width=True)

with col1:
    fig = draw_bridge(bridge_data)
    selection = st.plotly_chart(fig, on_select="rerun", selection_mode="points", key="bridge_chart")

    if selection and hasattr(selection, "selection") and selection.selection.points:
        clicked_point = selection.selection.points[0]
        if "customdata" in clicked_point:
            customdata = clicked_point["customdata"]
            target = customdata[0] if isinstance(customdata, list) else customdata
            if isinstance(target, str) and "_" in target and st.session_state.sensors.get(target) != active_sensor:
                st.session_state.sensors[target] = active_sensor
                st.rerun()

# --- RESULTS DASHBOARD ---
if run_sim:
    if not st.session_state.sensors:
        st.warning("Please place at least one sensor on the bridge before running the simulation!")
    else:
        st.divider()
        st.subheader("📈 Sensor Telemetry Data")
        
        try:
            load_positions, sim_results = run_moving_load(bridge_data, st.session_state.sensors)
        except ValueError as exc:
            st.error(f"Simulation cannot run for this bridge: {exc}")
            st.stop()
        
        units_by_type = {
            "Displacement": "Deflection (m)",
            "Strain Gauge": "Axial Force (kN)",
            "Accelerometer": "Acceleration (m/s^2)",
        }

        # Split plots by sensor type so each chart uses a single, meaningful unit.
        for sensor_type in SENSOR_TYPES:
            traces = []
            for sensor_target, data_array in sim_results.items():
                if st.session_state.sensors.get(sensor_target) != sensor_type:
                    continue

                traces.append(
                    go.Scatter(
                        x=load_positions,
                        y=data_array,
                        mode="lines+markers",
                        name=sensor_target,
                        line=dict(color=SENSOR_TYPES[sensor_type]["color"]),
                    )
                )

            if not traces:
                continue

            st.markdown(f"**{sensor_type} Sensors**")
            res_fig = go.Figure(data=traces)
            res_fig.update_layout(
                xaxis_title="Truck Position Along Bridge (X-coordinate)",
                yaxis_title=units_by_type[sensor_type],
                hovermode="x unified",
                height=360,
            )
            st.plotly_chart(res_fig, use_container_width=True)